services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus-observer-${CONFIG_NAME}
    volumes:
       - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
       - ./monitoring:/etc/prometheus:ro
    restart: always
    networks:
      observer_network:
        aliases:
          - prometheus-observer-${CONFIG_NAME}

  grafana:
    image: grafana/grafana
    container_name: grafana-observer-${CONFIG_NAME}
    restart: always
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      observer_network:
        aliases:
          - grafana-observer-${CONFIG_NAME}

  # alertmanager:
  #   image: prom/alertmanager
  #   container_name: alertmanager-observer-${CONFIG_NAME}
  #   restart: always
  #   ports:
  #     - "9093:9093"
  #   volumes:
  #     - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  #   networks:
  #     observer_network:
  #       aliases:
  #         - alertmanager-observer-${CONFIG_NAME}


  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter-observer-${CONFIG_NAME}
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    networks:
      observer_network:
        aliases:
          - node-exporter-observer-${CONFIG_NAME}


  loki:
    image: grafana/loki:2.9.3
    container_name: loki-observer-${CONFIG_NAME}
    restart: always
    volumes:
      - ./monitoring/loki-config.yml:/etc/loki/config.yml
      - ./monitoring/loki-data:/loki
    networks:
      observer_network:
        aliases:
          - loki-observer-${CONFIG_NAME}

  promtail:
    image: grafana/promtail:2.9.3
    container_name: promtail-observer-${CONFIG_NAME}
    restart: always
    volumes:
      - ./logs:/app/logs            
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      observer_network:
        aliases:
          - promtail-observer-${CONFIG_NAME}

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-observer-${CONFIG_NAME}
    restart: always
    ports:
      - "${JAEGER_UI_PORT}:16686"  # UI
    networks:
      observer_network:
        aliases:
          - jaeger-observer-${CONFIG_NAME}


volumes:
  grafana-storage:

networks:
  observer_network:
    external: true
